<?php

namespace Urcalanda\Control;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-09-30 at 17:16:44.
 */
class RegExprTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var RegExpr
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new RegExpr();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Urcalanda\Control\RegExpr::getRegExpr
     */
    public function testGetRegExpr()
    {
        $this->assertEquals('',$this->object->getRegExpr());
    }

    /**
     * @covers Urcalanda\Control\RegExpr::setRegExpr
     */
    public function testSetRegExpr()
    {
        $this->object->setRegExpr('regExpr');
        $this->assertEquals('regExpr',$this->object->getRegExpr());
    }

    /**
     * @covers Urcalanda\Control\RegExpr::getPriority
     */
    public function testGetPriority()
    {
        $this->assertEquals(RegExpr::PRIORITY_BY_DEFAULT,$this->object->getPriority());
   }

    /**
     * @covers Urcalanda\Control\RegExpr::setPriority
     */
    public function testSetPriority()
    {
        $this->object->setPriority(10);
        $this->assertEquals(10,$this->object->getPriority());
    }

    /**
     * @covers Urcalanda\Control\RegExpr::getCommand
     */
    public function testGetCommand()
    {
        $this->assertNull($this->object->getCommand());
    }

    /**
     * @covers Urcalanda\Control\RegExpr::setCommand
     * @todo   Implement testSetCommand().
     */
    public function testSetCommand()
    {
        $myCommand = new Command('');

        $this->object->setCommand($myCommand);
        $this->assertNotNull($this->object->getCommand());
    }

}
